# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Statistiline andmeteadus ja visualiseerimine
tagline:          MTMS.01.100
url:              http://andmeteadus.github.io
paginate:         1
baseurl:          2015/
author:
  name:           Tanel Pärnamaa, Kaspar Märtens
  url:            
  email:          andmeteadus@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           http://andmeteadus.github.io/2015

pages_list:       
  Praktikumid: '/praktikumid'
  Projektid: '/projektid'